# Generated by Django 5.0.3 on 2024-04-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_courseoffer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseOffer",
        ),
    ]
